export const cuisineList = [
    "Indian",
    "Punjabi",
    "South Indian",
    "Mughlai",
    "North Indian",
    "Bengali",
    "Gujurati",
    "Hyderabadi",
    "Karnataka",
    "Andhra",
    "Kerala",
    "Awadhi",
    "Kebabs",
    "Street Food",
    "Sweets",
    "Seafood",
    "Rajasthani",
    "Chaat",
    "Goan",
    "Portuguese-inspired",
    "Beachside Snacks",
    "Tandoor",
    "Dhaba-style",
    "Vegetarian",
    "Tamil",
    "Chettinad",
    "Biryani",
    "Thali",
    "Farsan",
    "Spicy",
    "Malabar",
    "Tamil Nadu",
    "Marwari",
    "Telangana",
    "Non-vegetarian",
    "Curries",
    "Desserts",
    "Idli",
    "Filter Coffee",
    "Vada",
    "Snacks",
    "Lassi",
    "Spanish",
    "Steak",
    "Sushi",
    "Tacos",
    "Tapas",
    "Vegan",
  ];